---
- name: Look Register Test
  gather_facts: no
  hosts: localhost
  tasks:
    - name: Looping Echo Task
      shell: "echo this is my item: {{  item }}"
      loop:
        - one
        - two
      register: output
    - debug: 
        msg: "{{ item.stdout }}"
      with_items:"{{ output['reuslts']  }}"