---
# 파일 배포
# (ansible) custom.fact - 배포 > (web1) /etc/ansible/fact.d/custom.fact
- name: 사용자 정의 팩트 파일 배포하기
  hosts: webserver
  gather_facts: no
  tasks:
  - name: 폴더 만들기
    file:
      path: /etc/ansible/fact.d
      state: directory
      recurse: yes

  - name: 파일 배포하기
    copy:
      src: custom.fact
      dest: /etc/ansible/fact.d/custom.fact