---
- name: 잡 제어 플레이북 예제
  hosts: webservers
  gather_facts: yes
  vars_files:
  - vars/vars.yml
  tasks:
  - name: 시스템 사양 점검 - 메모리 & 베포판
    fail:
      msg: "{{ ansible_hostname}}'s Minimun memory: 256MB"
    when:
      - ansible_memfree_mb <= 256
      - ansible_distribution != 'CentOS'

  - name: 최신 패키지 설치
    yum:
      name: "{{ packages}}"
      state: latest

  - name: 웹 서비스 기동
    service:
      name: "{{  item  }}"
      state: started
      enabled: yes
    with_items: "{{ services}}"

  -name: 웹 서버 설정
    # /var/www/gtml/index 
    # /etc/pki/tls/private/localhost.key
    # /etc/localhost.crt -> /etc/pk1/tls/certs/localhost.
    copy:
      src: "{{ item.src}}"
      dest: "{{ item.dest}}"
    with_items: "{{ conf_files}}"
    notify: restart httpd

  handlers:
  - name: restart httpd
    service:
      name: httpd
      state: restarted