---
# 1)  방화벽 서비스 off - http(80/tcp), https(443/tcp)  =>firewall
# 2)   서비스 off - httpd => service
# 3)  서비스 설정 삭제 - /var/www/html/index.html => file
# 4)  패키지 삭제 - httpd, mod_Ssl => yum

- name: 인트라넷 웹 서버 설정 복원 작업
  hosts:  web1
  tasks:
    # 1) 방화벽 포트 닫기 - http, https
  - name: "(1) 방화벽 포트 닫기 - http(80/tcp), https(443/tcp)"
    firewalld:
      port:  "{{ item }}"
      permanent: yes
      immediate: yes
      state: disabled
    loop:
      - 80/tcp
      - 443/tcp
    # 2) 서비스 off -  httpd, 
  - name: "(2) 서비스 off -  httpd, "
    service:
      name:  "httpd" 
      state:  stopped
      enabled: no
    loop:
      - httpd
    # 3) 웹 서비스 삭제 - /var/www/html/index.html
  - name: "(3) 웹 서비스 삭제  - /var/www/html/index.html"
    file:
      path: /var/www/html/index.html
      state: absent
    # 4) 패키지 삭제- httpd, mod_ssl,
  - name: "(4) 패키지 삭제- - httpd, mod_ssl"
    yum:
      name:
        - httpd 
        - mod_ssl
      state:  absent



