---
- name: Install and start Apache HTTPD
  hosts: all
  tasks:
    - name: Configuration firewall (re)
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: disabled

    - name: httpd is started
      service:
        name: httpd
        state: stopped
        enabled: no

    - name: Correct index.html is present
      file:
        path: /var/www/html/index.html
        state: absent

    - name: httpd package is present
      yum:
        name: httpd
        state: absent
