---
# 1) 방화벽 서비스 OFF - http, https, mysql => firewalld
# 2) 서비스 disable - httpd, mariadb => service
# 3) 서비스 디렉토리 삭제 - /var/www/html => file
# 4) 패키시 삭제 -....=> yum|dnf

- name: "DB 복원작업"
  hosts: web1
  tasks:
  #    1 * 방화벽에 off : http, https
  - name:  "방화벽에 off  : http, https"
    firewalld:
      service: "{{ item }}"
      permanent: yes
      immediate: yes
      state: disabled
    loop:
      - http
      - https
      - mysql
  #    2 * 웹 패키지 기동  : httpd
  - name: "WEB + DB 서비스 disable"
    service:
      name: "{{ item }}"
      state:  stopped
      enabled: no
    loop:
      - httpd
      - mariadb
# 3) 웹 서비스 삭제 - /var/www/html/index.php
  - name: "(3) 웹 서비스 삭제  - /var/www/html/index.php"
    file:
      path: /var/www/html/index.php
      state: absent
#   4.  * 웹 패키지 삭제 
  - name: 패키지 삭제 
    yum:
      name:
        - php
        - php-mysqlnd
        - php-pdo
        - mariadb-server
        - mariadb
        - python3-pip
      state: absent







